default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  port: 5432
  username: apple
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: https_development

test:
  <<: *default
  database: https_test

production:
  primary: &primary_production
    <<: *default
    database: https_production
    username: apple
    password: <%= ENV["HTTPS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: https_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: https_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: https_production_cable
    migrations_paths: db/cable_migrate
